### ISSUE TITLE
Threads Flag & Missing Mutation

### ISSUE THREAD

**Issue by jaikishantulswani** [Josue87/gotator#5]
@Josue87 Can you please add a flag to control the number of `threads` meanwhile I also found that `gotator` is missing one mutation when we don't want to use `depth` flag so this would be in default mutation list but it is **missing**
words:
```
junk
```

domain:
```
new.example.com
```
command
```
gotator -sub domain -perm words -md | sort -u
```
Result
```
example.com
junk.example.com
junk-new.example.com
junk.new.example.com
junknew.example.com
new.example.com
new-junk.example.com
newjunk.example.com
new-new.example.com
newnew.example.com
```

As you see it is missing `new.junk.example.com` when it is having `new-junk.example.com`, results are also containing duplicates

**Comment by Josue87** [comment]
Hello @jaikishantulswani,

You have the flag `t` to control threads, but it is a tool that runs constantly with the output, so many threads may even worsen the runtime.

In the other question, try to execute:

` gotator -sub domain -perm words -md -mindup | uniq`

The result is as follows:

```
example.com
junk.example.com
new.example.com
junk.new.example.com
junk-new.example.com
junknew.example.com
newjunk.example.com
new-junk.example.com
```

It is impossible to remove all duplicates from the output, so I use uniq.

**Comment by jaikishantulswani** [comment]
@Josue87 Thank you :+1:

**Comment by jaikishantulswani** [comment]
@Josue87 One more thing, can it be possible to add like: in default mutation without providing depth, like providing depth 2 make a huge file

domains
```
new-old.example.com
```

words
```
space
```

```
old.new.space.example.com
old-new.space.example.com
space-old.new.example.com
space-old-new.example.com
new-space.old.example.com
new-space-old.example.com
```

**Comment by Josue87** [comment]
When I have time I will look at how this task can be accomplished.

Thanks for the idea @jaikishantulswani

**Comment by Josue87** [comment]
Hello @jaikishantulswani!

I have been checking the functionality you told me about, finally it has not been added, because depth 1 should be as light as possible, if we add a lot of subdomains and/or permutations it generates more information than desired.

However, from your idea I have added the possibility that given `new-old.example.com`, it can be extracted as permutations `new-old`, `old` and `new`.

For large number of permutations I recommend depth 1, however if you are going to work with less workload you can use depth 2 or 3 to achieve the result you are looking for.

Thanks!

**Comment by jaikishantulswani** [comment]
@Josue87 Thank you
